name: keepalive

on:
  schedule:
    - cron: "*/5 * * * *"   # 每 5 分鐘 ping 一次（GitHub Actions 時區是 UTC）
  workflow_dispatch:        # 可手動觸發
jobs:
  ping:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Ping Render health endpoint
        run: |
          curl -fsS -m 10 -o /dev/null "https://dash16.onrender.com/healthz" || true
